### ISSUE TITLE
Executables don't seem to honor -conf parameter

### ISSUE THREAD

**Issue by Mazecreator** [UnitaNetwork/unita#1]
Passing the -conf=/local/file/myblockchain.conf does not seem to be honored by any of the 0.16 utilities.

This requires PRIVATE chains to be declared on a public website to use the "-chain=" command-line option which is not desirable.  This gives a catalog of private chains to attack.

This appears to be a problem in the util.cpp, I cannot find any place where "-conf" is obtained from the command-line.

**Comment by lickey777** [comment]
Unitad will search default path (~/Library/Application Support/Unita in MacOS). For example, if we want to launch 'xunit'a(https://chain.unita.network/#/chain/view?chainId=xunita), unitad will search configuration in ~/Library/Application Support/Unita/chain_xunita/unita.conf (note: all .conf need to be named ad unita.conf) and load chain 'xunita'. So if you don't want to use the "-chain=" command-line option, you can use "-datadir=xxx/xxx/chain_xunita" and copy configuration content of xunita(https://chain.unita.network/chain/xunita.conf) to 'xxx/xxx/chain_xunita/unita.conf'.
    And '-conf=' is valid in unitad, maybe you get wrong content in unita.conf. Please show me your '.conf' and I will check it.

**Comment by lickey777** [comment]
Unitad will search default path (~/Library/Application Support/Unita in MacOS). For example, if we want to launch 'xunit'a(https://chain.unita.network/#/chain/view?chainId=xunita), unitad will search configuration in ~/Library/Application Support/Unita/chain_xunita/unita.conf (note: all .conf need to be named ad unita.conf) and load chain 'xunita'. So if you don't want to use the "-chain=" command-line option, you can use "-datadir=xxx/xxx/chain_xunita" and copy configuration content of xunita(https://chain.unita.network/chain/xunita.conf) to 'xxx/xxx/chain_xunita/unita.conf'.
And '-conf=' is valid in unitad, maybe you get wrong content in unita.conf. Please show me your '.conf' and I will check it.

**Comment by web3lickey777** [comment]
Unitad will search default path (~/Library/Application Support/Unita in MacOS). For example, if we want to launch 'xunit'a(https://chain.unita.network/#/chain/view?chainId=xunita), unitad will search configuration in ~/Library/Application Support/Unita/chain_xunita/unita.conf (note: all .conf need to be named ad unita.conf) and load chain 'xunita'. 

So if you don't want to use the "-chain=" command-line option, you can use "-datadir=xxx/xxx/chain_xunita" and copy configuration content of xunita(https://chain.unita.network/chain/xunita.conf) to 'xxx/xxx/chain_xunita/unita.conf'.

And '-conf=' is valid in unitad, maybe you get wrong content in unita.conf. Please show me your '.conf' and I will check it.
